services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      # <host port>:<container port>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /c/Users/GAMER/Desktop/codigos/Rocketseat/Python/Módulo 4/sample-flask-auth/mysql/:/var/lib/mysql